### ISSUE TITLE
Compile error in hidden module "mGetVisibleRange" on 64-bit Word

### ISSUE THREAD

**Issue by CaptainPious** [cxw42/VimWord#12]
I'm currently using Microsoft Word 2013 (64-bit), and I seem to be getting an error trying to run this using an Add-in shortcut. Since you didn't explicitly mention it, does the Add-in also work on the 64-bit version of Microsoft Word?

**Comment by cxw42** [comment]
Thanks for trying VimWord - you are the first user I know of other than myself! :)

It should work on 64-bit.  I unfortunately do not have access to 2013 at the moment.  I'll try it on 2016 and see if I find any clues.

Could you give me any more details of the error message?  Does it only happen when trying to use the shortcut?  Does it work through the Macros dialog?  Also, what OS version?

Much appreciated!

**Comment by cxw42** [comment]
Turns out my 2016 is 32-bit (`Word 2016 MSO (16.0.12325.20280) 32-bit`), and it works.  Sorry I can't test on 64-bit!

I do have a guess.  `mGetVisibleRange` uses Windows API functions that take `Long` arguments, and the size of `Long` is different between 32-bit and 64-bit ([ref](https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/64-bit-visual-basic-for-applications-overview)).  I will see what I can do about updating the code to run in 64-bit environments.

**Comment by CaptainPious** [comment]
Thank you so much for getting back to me! I have to use Microsoft Word for work and thought this could be helpful since I normally use Vim.

It also does not work through the Macros dialog; I get the same error message. Though, I did have a question about that, too. Although I've tried them all, I see these four options in Macro dialog. 

*VimWord.VimDoCommand
*NewMacros.VimDoCommand
*VimCommandLoop
*VimDoCommand_About 

VimWord.VimDoCommand is the one I need, right?

My OS is Microsoft Windows 10 Pro 64-bit.

I would've downloaded the 32-bit version of Microsoft Works, but I do not have the option to do that, unfortunately.

Please let me know if you need any other information!

**Comment by cxw42** [comment]
Thanks for the info!  VimWord.VimDoCommand is indeed the one.  The NewMacros entry is a bit strange - you can probably delete it if you didn't create it yourself on purpose.

I'll see what I can do!

**Comment by cxw42** [comment]
Please give `master` a try and let me know how it goes!  Unfortunately, I can't test the code since I don't have a 64-bit machine.  If you do get any error messages, please send me as much detail as you can.

For testing, rather than installing, please:
- Uninstall VimWord
- clone the repo into a directory of your choice (if you haven't already)
- Open Word
- Hit Alt+F11 to open the VB editor
- Back in the main Word window, open VimWord.dotm from the directory where you cloned it.

That will give you better error messages in the VB editor than you get if you install and then open Word.  For example, the line number is in the top toolbar of the VB editor --- if you can point me to specific line numbers that Word complains about, I will be able to fix  them more easily.  Thanks!

**Comment by CaptainPious** [comment]
Sorry for the late response! Whatever you did, worked! Both my home and work computers are running 64-bit Microsoft Word, and I haven't run into any issues so far.  Thank you so much! I think it's safe to close this issue.

**Comment by cxw42** [comment]
Great news!  Happy Vimming :) !

**Comment by cxw42** [comment]
@CaptainPious Just checking back - how's it going?  If VimWord is working for you, would you be willing to star the project here on GitHub?  I would appreciate the support!
